App.js, redux/folderReducer.js, redux/store.js
1. Initialized redux store 
2. Created folder reducer
Enable store access globally 
Redux toolkit
Closes #16
=> feat(redux):initial store setup

README.md, components/AddNewItemMenu.js, components/QrContainer.js, components/TopBar.js, components/UrlModal.js, components/addNewItemMenu.js, components/folder/FolderContainer.js, components/folder/FolderContent.js, components/folder/FolderForm.js, components/folder/LinksContainer.js, components/folder/NewFolderPage.js, components/folder/folderContainer.js, components/folder/folderContent.js, components/folder/folderForm.js, components/folder/linksContainer.js, components/folder/newFolderPage.js, components/qrContainer.js, components/topBar.js, components/urlModal.js
1. Created README.md
2. Created component file structure 
Closes #3
=> Ds 3 project architecture

components/QrContainer.js, package.json, redux/folderSlice.js, yarn.lock
1. Created inputs to accept new link information
2. Connected input to redux to store links in selected folder
3.  Implemented UUID
4. Arranged payload to fit data model
_Describe the problem or feature in addition to a link to the issues._
To dynamically add new links to selected folders.
Redux
Closes #5
=> Data model implementation

components/UrlModal/UrlModal.js, components/folder/IndividualFolder/styles.js, components/folder/NewFolderModal/NewFolderModal.js, components/folder/NewFolderModal/styles.js, redux/folderSlice.js
1. Implement new folder functionality
2. Add new folder functionality in redux
3. Handle new folder error checking for input field validation
To be able to add a new folder for QR Codes. Better UX and organization. Implement folder creation from Redux. 
Closes #7
=> Ds 7 add folder functionality

components/folder/FolderContainer/FolderContainer.js, components/folder/IndividualFolder/IndividualFolder.js, components/folder/NewFolderModal/NewFolderModal.js, components/folder/NewFolderModal/styles.js, redux/folderSlice.js, redux/modalSlice.js
1. Allow users to edit current folder data
2. Create editMode modal
So users have the option to edit the name, description and color coding of their current folders.
Redux
Closes #8
=> Edit folder functionality

redux/folderSlice.js
1. Fix delete folder button functionality
For delete button inside edit folder modal to work properly
Closes #47
=> bug(folder-slice): fix delete folder bug 

components/AddNewItemMenu/AddNewItemMenu.js, components/folder/FolderActionPage/FolderActionPage.js, components/folder/FolderActionPage/styles.js
1. Dynamically render URL links in edit folder
2. Populate folder name and description placeholders in edit folder
To display additional folder information when a user clicks on the edit folder button
Closes #51
=> Ds 51 folder description and links

components/UrlModal/UrlModal.js, components/UrlModal/styles.js, package.json, yarn.lock
1. Install React Native Picker
2. Use Picker to select folders to place saved URLs
_Describe the problem or feature in addition to a link to the issues._
So users are able to select the folder they would like to save a new QR code to.
Closes #55
=> Implement folder picker

components/EditUrlModal/EditUrlModal.js, components/folder/EditFolderPage/EditFolderPage.js, redux/folderSlice.js, utils/toastNote.js
1. Implement delete link functionality
2. Add delete link reducer
3. add toast for deletion confirmation
Closes #14 
Closes #15
=> feat(delete-link): implement delete link functionality, add toast notification

README.md, components/AddOrScanModal/AddOrScanModal.js, components/AddOrScanModal/styles.js, components/BarcodeScanner/BarcodeScanner.js, components/Dashboard/Dashboard.js, components/EditUrlModal/EditUrlModal.js, components/UrlModal/UrlModal.js, components/folder/AddFolderPage/AddFolderPage.js, components/folder/EditFolderPage/EditFolderPage.js, redux/modalSlice.js, utils/toastNote.js
1. Hooked up barcode scanner
2. Saved barcode scanner data to redux state
3. Saved scanned code as new link to folders
4. Implement success toast on a successful scan
Users are able to scan QR codes to save to the app.
Closes #63
=> Scan QR code

README.md, components/EditUrlModal/EditUrlModal.js, components/folder/AddFolderPage/AddFolderPage.js
1. Implement edit/delete url functionality from add folder page
So users have the ability to edit and delete newly added links from the add folder page
Closes #67
=> Eedit and delete url functionality from add folder page

components/QrContainer/QrContainer.js, components/QrContainer/styles.js, package.json, redux/qrSlice.js, yarn.lock
1. Install expo web browser package
2. Implement webview on user clicking URL link
For the user to click on currently selected qr link to open in a web browser
Closes #61
=> feat(webview): enable qr link webview

App.js, package.json, redux/store.js, yarn.lock
1. install async storage
2. install redux-persist
3. implement local storage for folder slice
For the user to be able to exit the app, and have all their data once they open the app again.
Closes #32
=> feat(data-persistence): implement redux persist and async storage

components/Dashboard/Dashboard.js
1. install expo status bar
2. Import status bar and call a <StatusBar /> component with default style of "light"
3. Verified that orientation: "portrait" works as expected. 
To change the default color of the status bar, to a light theme. Creates a better readability contrast with our UI colors.
Closes #79 
Closes #80
=> feat(statusbar): implement light mode default for status bar color

components/AddNewItemMenu/AddNewItemMenu.js, components/BarcodeScanner/BarcodeScanner.js, components/EditUrlModal/EditUrlModal.js, components/QrContainer/QrContainer.js, components/TopBar/TopBar.js, components/UrlModal/UrlModal.js, components/folder/AddFolderPage/AddFolderPage.js, components/folder/EditFolderPage/EditFolderPage.js, components/folder/IndividualFolder/IndividualFolder.js
1.Added hitslop to pressable icons
To make Icons eaiser for users to press
Closes #85
=> Add hitslop to necessary pressable icons

components/folder/EditFolderPage/EditFolderPage.js, components/folder/FolderContainer/FolderContainer.js
1. Hooked up buttons up to proper functions
Buttons were not hooked up to correct functions
Closes #94
=> feat(app): hook up buttons to proper functions

package.json
=> version bump 0.1.0

components/AddNewItemMenu/styles.js, components/Dashboard/Dashboard.js, components/Dashboard/styles.js, components/TopBar/styles.js, components/UrlModal/UrlModal.js, components/UrlModal/styles.js, components/folder/AddFolderPage/AddFolderPage.js, components/folder/AddFolderPage/styles.js, components/folder/EditFolderPage/EditFolderPage.js, components/folder/EditFolderPage/styles.js, components/folder/IndividualFolder/IndividualFolder.js, components/folder/LinksContainer/LinksContainer.js, utils/toastNote.js
1. Fix styles for Android OS
2. Fix Scanner in add url modal
So styling is consistent for both IOS and Android
Closes #104
=> Styling for android and Scan fix

components/AddNewItemMenu/AddNewItemMenu.js, components/BarcodeScanner/BarcodeScanner.js, components/EditUrlModal/EditUrlModal.js, components/UrlModal/UrlModal.js, components/folder/EditFolderPage/EditFolderPage.js, package.json, utils/toastNote.js, yarn.lock
1. Link Validation
2. Clear and populate the input values accordingly
Prevent users from submitting an empty URL input
Redux
Closes #107
=> Adding link validation

app.json, eas.json, package.json
1. Configure EAS build
2. Version Bump to 0.1.1
configure eas release channels for upcoming release
Utilize eas cli
=> Configure eas and version bump to 0.1.1
